name: Build Rust App

on:
  release:
    types: [created]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-apple-darwin
        override: true

    - name: Build for Apple Silicon
      run: |
        # Create a basic Info.plist
        cat > Info.plist << EOL
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>LSUIElement</key>
            <true/>
        </dict>
        </plist>
        EOL

        # Build the binary
        cargo build --release --target aarch64-apple-darwin

        # Create the minimal app bundle structure
        mkdir -p target/aarch64-apple-darwin/release/mini-badger.app/Contents/MacOS
        cp target/aarch64-apple-darwin/release/mini-badger target/aarch64-apple-darwin/release/mini-badger.app/Contents/MacOS/
        cp Info.plist target/aarch64-apple-darwin/release/mini-badger.app/Contents/

        # Create a launcher script
        cat > target/aarch64-apple-darwin/release/mini-badger << EOL
        #!/bin/bash
        exec "\$(dirname "\$0")/mini-badger.app/Contents/MacOS/mini-badger" "\$@"
        EOL
        chmod +x target/aarch64-apple-darwin/release/mini-badger

    - name: Get SHA256
      run: |
        echo "BINARY_SHA=$(shasum -a 256 target/aarch64-apple-darwin/release/mini-badger | awk '{print $1}')" >> $GITHUB_ENV

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: target/aarch64-apple-darwin/release/mini-badger
        tag_name: ${{ github.event.release.tag_name }}

    - name: Update Homebrew Formula
      run: |
        git clone https://${{ secrets.TAP_TOKEN }}@github.com/${{ github.repository_owner }}/homebrew-tap.git
        cd homebrew-tap

        cat > mini-badger.rb << EOL
          class MiniBadger < Formula
            desc "Your mini-badger description"
            homepage "https://github.com/${{ github.repository }}"
            version "${GITHUB_REF#refs/tags/v}"

            if OS.mac?
              url "https://github.com/${{ github.repository }}/releases/download/${GITHUB_REF#refs/tags/}/mini-badger"
              sha256 "${BINARY_SHA}"
            end

            service do
              run opt_bin/"mini-badger"
              keep_alive true
              log_path var/"log/mini-badger.log"
              error_log_path var/"log/mini-badger.error.log"
            end

            def install
              prefix.install "mini-badger.app"
              bin.install "mini-badger"
            end
          end
        EOL

        git config user.name github-actions
        git config user.email github-actions@github.com
        git add mini-badger.rb
        git commit -m "Update mini-badger to ${GITHUB_REF#refs/tags/}"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.TAP_TOKEN }}
